### ISSUE TITLE
Nonsensical "Authentication failed" message when trying to apply updates, after NOT asking me for sudo password

### ISSUE THREAD

**Issue by php4fan** [manjaro/pamac#528]
This is what I did:

- opened Pamac GUI
- went to Updates (all available updates were checked by default)
- clicked Apply
- At some point I was prompted for the sudo password and I entered it
- It went on doing stuff, I have no idea how much it actually installed (actually I think nothing) and how much it only downloaded, built, prepared, or whatever. Telling whatever the **** Pamac is really doing is quite hard unless you know about its inner workings
- At some point there was an error, and while I assume it's not Pamac's fault, I suspect it somehow _triggered_ the issue (which will come shortly). This was the error:

<img width="608" height="361" alt="Image" src="https://github.com/user-attachments/assets/b91845e4-3c89-4ce8-8bcd-3e453ae3c84b" />

Afer this, it went back to the list of available updates, all checked, so:
- I clicked Apply again

At this point, I got this stupid error:

<img width="601" height="345" alt="Image" src="https://github.com/user-attachments/assets/26602915-4079-4136-bc9f-f8b07d4dc848" />

I say "stupid error" because this makes no sense.
First of all, it should be clearer as to WHAT authentication failed. Is it Pamac trying to authenticate to some server, or what? But I assume it's the user's authentication as a sudoer.

An error message with "authentication failed" only makes sense just after entering a password. If you didn't ask me for a password and I'm not authenticated, or if my entering the password a few minutes ago is for whatever reason no longer enough, ask me for the password again. Only then, if I enter it wrong, does "authentication failed" make sense. If I have not just been prompted for a password, and anything authentication-related fails, yous should first ask me for the password and try again before you emit any error message.

**Comment by guinux** [comment]
fixed with https://github.com/manjaro/libpamac/commit/35f1ab2da94fae503e5d995dae09c0dd495afecf

**Comment by Megabobster** [comment]
Still having this issue on 11.7.4-2, though it was triggered by cancelling a long AUR build instead of an error.
